language: java
jdk:
  - openjdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
  
addons:
  sonarcloud:
    organization: "springdoc-openapi"
    token:
      secure: "$SONAR_TOKEN"

script:
  - mvn clean package sonar:sonar -Dsonar.projectKey=springdoc_springdoc-openapi-maven-plugin

deploy:
  provider: script
  script: mvn deploy -DskipTests --settings settings.xml
  on:
    branch: master

  
  
