language: java
jdk:
  - openjdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
  
addons:
  sonarcloud:
    organization: "springdoc-openapi"

script:
  - mvn clean package sonar:sonar -Dsonar.projectKey=springdoc_springdoc-openapi-maven-plugin -Dsonar.scanner.force-deprecated-java-version-grace-period=true

deploy:
  provider: script
  script: mvn deploy -DskipTests --settings settings.xml
  on:
    branch: master

  
  
